INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  1,
                  'A.3.10.1',
                  'Acueducto-captación',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  2,
                  'A.3.10.2',
                  'Acueducto- aducción',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  3,
                  'A.3.10.3',
                  'Acueducto- almacenamiento',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  4,
                  'A.3.10.4',
                  'Acueducto- tratamiento',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  5,
                  'A.3.10.5',
                  'Acueducto- conducción',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  6,
                  'A.3.10.6',
                  'Acueducto- macromedición',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  7,
                  'A.3.10.7',
                  'Acueducto-distribución',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  8,
                  'A.3.10.8',
                  'Acueducto- micromedición',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  9,
                  'A.3.10.9',
                  'Acueducto- índice de agua no contabilizada',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  10,
                  'A.3.10.1',
                  ' Acueducto-preinversiones, estudios',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  11,
                  'A.3.10.1',
                  ' Acueducto-interventoría',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  12,
                  'A.3.10.1',
                  ' Acueducto- formulación, implementación y acciones de fortalecimiento para la administración y opera',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  13,
                  'A.3.10.1',
                  ' Acueducto- subsidios',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  14,
                  'A.3.11.1',
                  'Alcantarillado- recolección',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  15,
                  'A.3.11.2',
                  'Alcantarillado - transporte',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  16,
                  'A.3.11.3',
                  'Alcantarillado- tratamiento',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  17,
                  'A.3.11.4',
                  'Alcantarillado- descarga',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  18,
                  'A.3.11.5',
                  'Alcantarillado-preinversiones, estudios',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  19,
                  'A.3.11.6',
                  'Alcantarillado-interventoría',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  20,
                  'A.3.11.7',
                  'Alcantarillado- fortalecimiento institucional',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  21,
                  'A.3.11.8',
                  'Alcantarillado- subsidios.',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  22,
                  'A.3.12.1',
                  'Aseo- proyecto de tratamiento y aprovechamiento de residuos sólidos',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  23,
                  'A.3.12.2',
                  'Aseo- maquinaria y equipos',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  24,
                  'A.3.12.3',
                  'Aseo- disposición final',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  25,
                  'A.3.12.4',
                  'Aseo- preinversión y estudios',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  26,
                  'A.3.12.5',
                  'Aseo-interventoría',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  27,
                  'A.3.12.6',
                  'Aseo-fortalecimiento institucional',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  28,
                  'A.3.12.7',
                  'Aseo- subsidios.',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  29,
                  'A.3.13',
                  'Transferencia pda inversión',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  30,
                  'A.3.14',
                  'Transferencia pda subsidios',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  31,
                  'A.3.15',
                  'Pago pasivos laborales',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_ACTIVIDAD_FUT (acfu_id,
                                  codigo,
                                  descripcion,
                                  fecha_modificacion,
                                  fecha_creacion,
                                  usu_creador,
                                  usu_modificador,
                                  activo)
        VALUES (
                  32,
                  'A.3.17',
                  'Pago de déficit de inversión en agua potable y saneamiento básico',
                  NULL,
                  TO_TIMESTAMP ('09/19/2016 00:00:00.00',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');COMMIT;