INSERT INTO GLUO_TIPO_FONDO_TESORERIA (tift_id,
                                         codigo,
                                         descripcion,
                                         fecha_creacion,
                                         fecha_modificacion,
                                         usu_creador,
                                         usu_modificador,
                                         activo)
        VALUES (
                  1,
                  'S',
                  'Subsidio',
                  TO_TIMESTAMP ('09/20/2016 17:20:07.251',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  NULL,
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_TIPO_FONDO_TESORERIA (tift_id,
                                         codigo,
                                         descripcion,
                                         fecha_creacion,
                                         fecha_modificacion,
                                         usu_creador,
                                         usu_modificador,
                                         activo)
        VALUES (
                  2,
                  'SP',
                  'Salud Publica',
                  TO_TIMESTAMP ('09/20/2016 17:20:28.980',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  NULL,
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_TIPO_FONDO_TESORERIA (tift_id,
                                         codigo,
                                         descripcion,
                                         fecha_creacion,
                                         fecha_modificacion,
                                         usu_creador,
                                         usu_modificador,
                                         activo)
        VALUES (
                  3,
                  'O',
                  'Oferta',
                  TO_TIMESTAMP ('09/20/2016 17:20:42.132',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  NULL,
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_TIPO_FONDO_TESORERIA (tift_id,
                                         codigo,
                                         descripcion,
                                         fecha_creacion,
                                         fecha_modificacion,
                                         usu_creador,
                                         usu_modificador,
                                         activo)
        VALUES (
                  4,
                  'GSI',
                  'Gastos Salud Inversion',
                  TO_TIMESTAMP ('09/20/2016 17:21:01.605',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  NULL,
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_TIPO_FONDO_TESORERIA (tift_id,
                                         codigo,
                                         descripcion,
                                         fecha_creacion,
                                         fecha_modificacion,
                                         usu_creador,
                                         usu_modificador,
                                         activo)
        VALUES (
                  5,
                  'GSF',
                  'Gastos Salud Funcionamiento',
                  TO_TIMESTAMP ('09/20/2016 17:21:14.277',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  NULL,
                  1,
                  NULL,
                  'A');COMMIT;