INSERT INTO GLUO_TIPO_INFORME_FUT (tiif_id,
                                     codigo,
                                     descripcion,
                                     fecha_modificacion,
                                     fecha_creacion,
                                     usu_creador,
                                     usu_modificador,
                                     activo)
        VALUES (
                  1,
                  'I',
                  'INVERSION',
                  NULL,
                  TO_TIMESTAMP ('09/13/2016 15:28:39.174',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_TIPO_INFORME_FUT (tiif_id,
                                     codigo,
                                     descripcion,
                                     fecha_modificacion,
                                     fecha_creacion,
                                     usu_creador,
                                     usu_modificador,
                                     activo)
        VALUES (
                  2,
                  'IN',
                  'INGRESOS',
                  NULL,
                  TO_TIMESTAMP ('09/13/2016 15:29:00.543',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_TIPO_INFORME_FUT (tiif_id,
                                     codigo,
                                     descripcion,
                                     fecha_modificacion,
                                     fecha_creacion,
                                     usu_creador,
                                     usu_modificador,
                                     activo)
        VALUES (
                  3,
                  'GF',
                  'GASTOS DE FUNCIONAMIENTO',
                  NULL,
                  TO_TIMESTAMP ('09/13/2016 15:29:11.831',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_TIPO_INFORME_FUT (tiif_id,
                                     codigo,
                                     descripcion,
                                     fecha_modificacion,
                                     fecha_creacion,
                                     usu_creador,
                                     usu_modificador,
                                     activo)
        VALUES (
                  4,
                  'SD',
                  'SERVICIO DE DEUDA',
                  NULL,
                  TO_TIMESTAMP ('09/13/2016 15:29:25.295',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_TIPO_INFORME_FUT (tiif_id,
                                     codigo,
                                     descripcion,
                                     fecha_modificacion,
                                     fecha_creacion,
                                     usu_creador,
                                     usu_modificador,
                                     activo)
        VALUES (
                  5,
                  'R',
                  'RESERVAS',
                  NULL,
                  TO_TIMESTAMP ('09/13/2016 15:29:38.15',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_TIPO_INFORME_FUT (tiif_id,
                                     codigo,
                                     descripcion,
                                     fecha_modificacion,
                                     fecha_creacion,
                                     usu_creador,
                                     usu_modificador,
                                     activo)
        VALUES (
                  6,
                  'CXP',
                  'CUENTAS POR PAGAR',
                  NULL,
                  TO_TIMESTAMP ('09/13/2016 15:29:53.960',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_TIPO_INFORME_FUT (tiif_id,
                                     codigo,
                                     descripcion,
                                     fecha_modificacion,
                                     fecha_creacion,
                                     usu_creador,
                                     usu_modificador,
                                     activo)
        VALUES (
                  7,
                  'VF',
                  'VIGENCIAS FUTURAS',
                  NULL,
                  TO_TIMESTAMP ('09/13/2016 15:30:13.240',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_TIPO_INFORME_FUT (tiif_id,
                                     codigo,
                                     descripcion,
                                     fecha_modificacion,
                                     fecha_creacion,
                                     usu_creador,
                                     usu_modificador,
                                     activo)
        VALUES (
                  8,
                  'FSEP',
                  'FONDO SALUD EJECUCION PRESUPUESTAL',
                  NULL,
                  TO_TIMESTAMP ('09/16/2016 16:07:55.997',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_TIPO_INFORME_FUT (tiif_id,
                                     codigo,
                                     descripcion,
                                     fecha_modificacion,
                                     fecha_creacion,
                                     usu_creador,
                                     usu_modificador,
                                     activo)
        VALUES (
                  9,
                  'FST',
                  'FONDO SALUD TESORERIA',
                  NULL,
                  TO_TIMESTAMP ('09/20/2016 17:23:05.608',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_TIPO_INFORME_FUT (tiif_id,
                                     codigo,
                                     descripcion,
                                     fecha_modificacion,
                                     fecha_creacion,
                                     usu_creador,
                                     usu_modificador,
                                     activo)
        VALUES (
                  10,
                  'A',
                  'AGUA',
                  NULL,
                  TO_TIMESTAMP ('09/20/2016 17:23:42.896',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  1,
                  NULL,
                  'A');COMMIT;