INSERT INTO GLUO_TIPO_DEUDA (tide_id,
                               codigo,
                               descripcion,
                               fecha_creacion,
                               fecha_modificacion,
                               usu_creador,
                               usu_modificador,
                               activo)
        VALUES (
                  1,
                  'I',
                  'Interna',
                  TO_TIMESTAMP ('09/16/2016 17:38:46.438',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  NULL,
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_TIPO_DEUDA (tide_id,
                               codigo,
                               descripcion,
                               fecha_creacion,
                               fecha_modificacion,
                               usu_creador,
                               usu_modificador,
                               activo)
        VALUES (
                  2,
                  'E',
                  'Externa',
                  TO_TIMESTAMP ('09/16/2016 17:38:53.591',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  NULL,
                  1,
                  NULL,
                  'A');COMMIT;