INSERT INTO GLUO_TIPO_OPERACION (tiop_id,
                                   codigo,
                                   descripcion,
                                   fecha_creacion,
                                   fecha_modificacion,
                                   usu_creador,
                                   usu_modificador,
                                   activo)
        VALUES (
                  1,
                  'M',
                  'Mortizacion',
                  TO_TIMESTAMP ('09/16/2016 17:38:19.302',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  NULL,
                  1,
                  NULL,
                  'A');INSERT INTO GLUO_TIPO_OPERACION (tiop_id,
                                   codigo,
                                   descripcion,
                                   fecha_creacion,
                                   fecha_modificacion,
                                   usu_creador,
                                   usu_modificador,
                                   activo)
        VALUES (
                  2,
                  'I',
                  'Intereses',
                  TO_TIMESTAMP ('09/16/2016 17:38:29.558',
                                'MM/DD/YYYY fmHH24fm:MI:SS.FF'),
                  NULL,
                  1,
                  NULL,
                  'A');COMMIT;