package com.unilever.bancoideas.modelo;
// Generated 9/08/2019 11:14:06 AM by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cargo generated by hbm2java
 */
public class Cargo  implements java.io.Serializable {


     private Integer cargId;
     private String codigo;
     private String nombre;
     private Double salario;
     private String auxilioTransporte;
     private String auxilioAlimentacion;
     private String usuCreador;
     private String usuModificacion;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private String estadoRegistro;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Cargo() {
    }

	
    public Cargo(Integer cargId, String codigo, String nombre, Double salario, String auxilioTransporte, String auxilioAlimentacion, String usuCreador, Date fechaCreacion, String estadoRegistro) {
        this.cargId = cargId;
        this.codigo = codigo;
        this.nombre = nombre;
        this.salario = salario;
        this.auxilioTransporte = auxilioTransporte;
        this.auxilioAlimentacion = auxilioAlimentacion;
        this.usuCreador = usuCreador;
        this.fechaCreacion = fechaCreacion;
        this.estadoRegistro = estadoRegistro;
    }
    public Cargo(Integer cargId, String codigo, String nombre, Double salario, String auxilioTransporte, String auxilioAlimentacion, String usuCreador, String usuModificacion, Date fechaCreacion, Date fechaModificacion, String estadoRegistro, Set<Empleado> empleados) {
       this.cargId = cargId;
       this.codigo = codigo;
       this.nombre = nombre;
       this.salario = salario;
       this.auxilioTransporte = auxilioTransporte;
       this.auxilioAlimentacion = auxilioAlimentacion;
       this.usuCreador = usuCreador;
       this.usuModificacion = usuModificacion;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.estadoRegistro = estadoRegistro;
       this.empleados = empleados;
    }
   
    public Integer getCargId() {
        return this.cargId;
    }
    
    public void setCargId(Integer cargId) {
        this.cargId = cargId;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Double getSalario() {
        return this.salario;
    }
    
    public void setSalario(Double salario) {
        this.salario = salario;
    }
    public String getAuxilioTransporte() {
        return this.auxilioTransporte;
    }
    
    public void setAuxilioTransporte(String auxilioTransporte) {
        this.auxilioTransporte = auxilioTransporte;
    }
    public String getAuxilioAlimentacion() {
        return this.auxilioAlimentacion;
    }
    
    public void setAuxilioAlimentacion(String auxilioAlimentacion) {
        this.auxilioAlimentacion = auxilioAlimentacion;
    }
    public String getUsuCreador() {
        return this.usuCreador;
    }
    
    public void setUsuCreador(String usuCreador) {
        this.usuCreador = usuCreador;
    }
    public String getUsuModificacion() {
        return this.usuModificacion;
    }
    
    public void setUsuModificacion(String usuModificacion) {
        this.usuModificacion = usuModificacion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


