package com.unilever.bancoideas.modelo;
// Generated 10/08/2019 06:53:15 PM by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HoraExtraEmpleado generated by hbm2java
 */
public class HoraExtraEmpleado  implements java.io.Serializable {


     private Integer hexmId;
     private TipoHoraExtra tipoHoraExtra;
     private Empleado empleado;
     private Date fecha;
     private Double cantidadHoras;
     private String usuCreador;
     private String usuModificador;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private String estadoRegistro;
     private Set<LiquidacionHoraExtra> liquidacionHoraExtras = new HashSet<LiquidacionHoraExtra>(0);

    public HoraExtraEmpleado() {
    }

	
    public HoraExtraEmpleado(Integer hexmId, Empleado empleado, Date fecha, Double cantidadHoras, String usuCreador, Date fechaCreacion, String estadoRegistro) {
        this.hexmId = hexmId;
        this.empleado = empleado;
        this.fecha = fecha;
        this.cantidadHoras = cantidadHoras;
        this.usuCreador = usuCreador;
        this.fechaCreacion = fechaCreacion;
        this.estadoRegistro = estadoRegistro;
    }
    public HoraExtraEmpleado(Integer hexmId, TipoHoraExtra tipoHoraExtra, Empleado empleado, Date fecha, Double cantidadHoras, String usuCreador, String usuModificador, Date fechaCreacion, Date fechaModificacion, String estadoRegistro, Set<LiquidacionHoraExtra> liquidacionHoraExtras) {
       this.hexmId = hexmId;
       this.tipoHoraExtra = tipoHoraExtra;
       this.empleado = empleado;
       this.fecha = fecha;
       this.cantidadHoras = cantidadHoras;
       this.usuCreador = usuCreador;
       this.usuModificador = usuModificador;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.estadoRegistro = estadoRegistro;
       this.liquidacionHoraExtras = liquidacionHoraExtras;
    }
   
    public Integer getHexmId() {
        return this.hexmId;
    }
    
    public void setHexmId(Integer hexmId) {
        this.hexmId = hexmId;
    }
    public TipoHoraExtra getTipoHoraExtra() {
        return this.tipoHoraExtra;
    }
    
    public void setTipoHoraExtra(TipoHoraExtra tipoHoraExtra) {
        this.tipoHoraExtra = tipoHoraExtra;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public Double getCantidadHoras() {
		return cantidadHoras;
	}


	public void setCantidadHoras(Double cantidadHoras) {
		this.cantidadHoras = cantidadHoras;
	}


	public String getUsuCreador() {
        return this.usuCreador;
    }
    
    public void setUsuCreador(String usuCreador) {
        this.usuCreador = usuCreador;
    }
    public String getUsuModificador() {
        return this.usuModificador;
    }
    
    public void setUsuModificador(String usuModificador) {
        this.usuModificador = usuModificador;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }

    public Set<LiquidacionHoraExtra> getLiquidacionHoraExtras() {
        return this.liquidacionHoraExtras;
    }
    
    public void setLiquidacionHoraExtras(Set<LiquidacionHoraExtra> liquidacionHoraExtras) {
        this.liquidacionHoraExtras = liquidacionHoraExtras;
    }




}


