package com.unilever.bancoideas.modelo;
// Generated 10/08/2019 06:53:15 PM by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * LiquidacionHoraExtra generated by hbm2java
 */
public class LiquidacionHoraExtra  implements java.io.Serializable {


     private Integer lhoeId;
     private HoraExtraEmpleado horaExtraEmpleado;
     private NominaEmpleado nominaEmpleado;
     private Double valor;
     private Double cantidadHoras;
     private Double totalPagar;
     private Double porcentaje;
     private String usuCreador;
     private String usuModificador;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private String estadoRegistro;

    public LiquidacionHoraExtra() {
    }

	
    public LiquidacionHoraExtra(Integer lhoeId, HoraExtraEmpleado horaExtraEmpleado, NominaEmpleado nominaEmpleado, Double valor, Double cantidadHoras, Double totalPagar, Double porcentaje, String usuCreador, Date fechaCreacion, String estadoRegistro) {
        this.lhoeId = lhoeId;
        this.horaExtraEmpleado = horaExtraEmpleado;
        this.nominaEmpleado = nominaEmpleado;
        this.valor = valor;
        this.cantidadHoras = cantidadHoras;
        this.totalPagar = totalPagar;
        this.porcentaje = porcentaje;
        this.usuCreador = usuCreador;
        this.fechaCreacion = fechaCreacion;
        this.estadoRegistro = estadoRegistro;
    }
    public LiquidacionHoraExtra(Integer lhoeId, HoraExtraEmpleado horaExtraEmpleado, NominaEmpleado nominaEmpleado, Double valor, Double cantidadHoras, Double totalPagar, Double porcentaje, String usuCreador, String usuModificador, Date fechaCreacion, Date fechaModificacion, String estadoRegistro) {
       this.lhoeId = lhoeId;
       this.horaExtraEmpleado = horaExtraEmpleado;
       this.nominaEmpleado = nominaEmpleado;
       this.valor = valor;
       this.cantidadHoras = cantidadHoras;
       this.totalPagar = totalPagar;
       this.porcentaje = porcentaje;
       this.usuCreador = usuCreador;
       this.usuModificador = usuModificador;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.estadoRegistro = estadoRegistro;
    }
   
    public Integer getLhoeId() {
        return this.lhoeId;
    }
    
    public void setLhoeId(Integer lhoeId) {
        this.lhoeId = lhoeId;
    }
    public HoraExtraEmpleado getHoraExtraEmpleado() {
        return this.horaExtraEmpleado;
    }
    
    public void setHoraExtraEmpleado(HoraExtraEmpleado horaExtraEmpleado) {
        this.horaExtraEmpleado = horaExtraEmpleado;
    }
    public NominaEmpleado getNominaEmpleado() {
        return this.nominaEmpleado;
    }
    
    public void setNominaEmpleado(NominaEmpleado nominaEmpleado) {
        this.nominaEmpleado = nominaEmpleado;
    }
    public Double getValor() {
        return this.valor;
    }
    
    public void setValor(Double valor) {
        this.valor = valor;
    }

    public Double getCantidadHoras() {
		return cantidadHoras;
	}


	public void setCantidadHoras(Double cantidadHoras) {
		this.cantidadHoras = cantidadHoras;
	}


	public Double getTotalPagar() {
        return this.totalPagar;
    }
    
    public void setTotalPagar(Double totalPagar) {
        this.totalPagar = totalPagar;
    }
    public Double getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(Double porcentaje) {
        this.porcentaje = porcentaje;
    }
    public String getUsuCreador() {
        return this.usuCreador;
    }
    
    public void setUsuCreador(String usuCreador) {
        this.usuCreador = usuCreador;
    }
    public String getUsuModificador() {
        return this.usuModificador;
    }
    
    public void setUsuModificador(String usuModificador) {
        this.usuModificador = usuModificador;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }




}


