package com.unilever.bancoideas.modelo;
// Generated 9/08/2019 11:14:06 AM by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * LiquidacionHoraExtra generated by hbm2java
 */
public class LiquidacionHoraExtra  implements java.io.Serializable {


     private Integer lhoeId;
     private NominaEmpleado nominaEmpleado;
     private TipoHoraExtra tipoHoraExtra;
     private Double valorRecargo;
     private Double valorHoraExtra;
     private Integer horasTrabajadas;
     private Double totalPagarRecargo;
     private Date fecha;
     private Double totalPagarHorasExtras;
     private String usuCreador;
     private String usuModificador;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private String estadoRegistro;

    public LiquidacionHoraExtra() {
    }

	
    public LiquidacionHoraExtra(Integer lhoeId, NominaEmpleado nominaEmpleado, TipoHoraExtra tipoHoraExtra, Double valorRecargo, Double valorHoraExtra, Integer horasTrabajadas, Double totalPagarRecargo, Date fecha, Double totalPagarHorasExtras, String usuCreador, Date fechaCreacion, String estadoRegistro) {
        this.lhoeId = lhoeId;
        this.nominaEmpleado = nominaEmpleado;
        this.tipoHoraExtra = tipoHoraExtra;
        this.valorRecargo = valorRecargo;
        this.valorHoraExtra = valorHoraExtra;
        this.horasTrabajadas = horasTrabajadas;
        this.totalPagarRecargo = totalPagarRecargo;
        this.fecha = fecha;
        this.totalPagarHorasExtras = totalPagarHorasExtras;
        this.usuCreador = usuCreador;
        this.fechaCreacion = fechaCreacion;
        this.estadoRegistro = estadoRegistro;
    }
    public LiquidacionHoraExtra(Integer lhoeId, NominaEmpleado nominaEmpleado, TipoHoraExtra tipoHoraExtra, Double valorRecargo, Double valorHoraExtra, Integer horasTrabajadas, Double totalPagarRecargo, Date fecha, Double totalPagarHorasExtras, String usuCreador, String usuModificador, Date fechaCreacion, Date fechaModificacion, String estadoRegistro) {
       this.lhoeId = lhoeId;
       this.nominaEmpleado = nominaEmpleado;
       this.tipoHoraExtra = tipoHoraExtra;
       this.valorRecargo = valorRecargo;
       this.valorHoraExtra = valorHoraExtra;
       this.horasTrabajadas = horasTrabajadas;
       this.totalPagarRecargo = totalPagarRecargo;
       this.fecha = fecha;
       this.totalPagarHorasExtras = totalPagarHorasExtras;
       this.usuCreador = usuCreador;
       this.usuModificador = usuModificador;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.estadoRegistro = estadoRegistro;
    }
   
    public Integer getLhoeId() {
        return this.lhoeId;
    }
    
    public void setLhoeId(Integer lhoeId) {
        this.lhoeId = lhoeId;
    }
    public NominaEmpleado getNominaEmpleado() {
        return this.nominaEmpleado;
    }
    
    public void setNominaEmpleado(NominaEmpleado nominaEmpleado) {
        this.nominaEmpleado = nominaEmpleado;
    }
    public TipoHoraExtra getTipoHoraExtra() {
        return this.tipoHoraExtra;
    }
    
    public void setTipoHoraExtra(TipoHoraExtra tipoHoraExtra) {
        this.tipoHoraExtra = tipoHoraExtra;
    }
    public Double getValorRecargo() {
        return this.valorRecargo;
    }
    
    public void setValorRecargo(Double valorRecargo) {
        this.valorRecargo = valorRecargo;
    }
    public Double getValorHoraExtra() {
        return this.valorHoraExtra;
    }
    
    public void setValorHoraExtra(Double valorHoraExtra) {
        this.valorHoraExtra = valorHoraExtra;
    }
    public Integer getHorasTrabajadas() {
        return this.horasTrabajadas;
    }
    
    public void setHorasTrabajadas(Integer horasTrabajadas) {
        this.horasTrabajadas = horasTrabajadas;
    }
    public Double getTotalPagarRecargo() {
        return this.totalPagarRecargo;
    }
    
    public void setTotalPagarRecargo(Double totalPagarRecargo) {
        this.totalPagarRecargo = totalPagarRecargo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Double getTotalPagarHorasExtras() {
        return this.totalPagarHorasExtras;
    }
    
    public void setTotalPagarHorasExtras(Double totalPagarHorasExtras) {
        this.totalPagarHorasExtras = totalPagarHorasExtras;
    }
    public String getUsuCreador() {
        return this.usuCreador;
    }
    
    public void setUsuCreador(String usuCreador) {
        this.usuCreador = usuCreador;
    }
    public String getUsuModificador() {
        return this.usuModificador;
    }
    
    public void setUsuModificador(String usuModificador) {
        this.usuModificador = usuModificador;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }




}


