package com.unilever.bancoideas.modelo;
// Generated 9/08/2019 11:14:06 AM by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer usuaId;
     private TipoUsuario tipoUsuario;
     private Persona persona;
     private Departamento departamento;
     private String usuario;
     private String contrasena;
     private String usuCreador;
     private String usuModifica;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private String estadoRegistro;

    public Usuario() {
    }

	
    public Usuario(Integer usuaId, TipoUsuario tipoUsuario, Persona persona, Departamento departamento, String usuario, String contrasena, String usuCreador, Date fechaCreacion, String estadoRegistro) {
        this.usuaId = usuaId;
        this.tipoUsuario = tipoUsuario;
        this.persona = persona;
        this.departamento = departamento;
        this.usuario = usuario;
        this.contrasena = contrasena;
        this.usuCreador = usuCreador;
        this.fechaCreacion = fechaCreacion;
        this.estadoRegistro = estadoRegistro;
    }
    public Usuario(Integer usuaId, TipoUsuario tipoUsuario, Persona persona, Departamento departamento, String usuario, String contrasena, String usuCreador, String usuModifica, Date fechaCreacion, Date fechaModificacion, String estadoRegistro) {
       this.usuaId = usuaId;
       this.tipoUsuario = tipoUsuario;
       this.persona = persona;
       this.departamento = departamento;
       this.usuario = usuario;
       this.contrasena = contrasena;
       this.usuCreador = usuCreador;
       this.usuModifica = usuModifica;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.estadoRegistro = estadoRegistro;
    }
   
    public Integer getUsuaId() {
        return this.usuaId;
    }
    
    public void setUsuaId(Integer usuaId) {
        this.usuaId = usuaId;
    }
    public TipoUsuario getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(TipoUsuario tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getUsuCreador() {
        return this.usuCreador;
    }
    
    public void setUsuCreador(String usuCreador) {
        this.usuCreador = usuCreador;
    }
    public String getUsuModifica() {
        return this.usuModifica;
    }
    
    public void setUsuModifica(String usuModifica) {
        this.usuModifica = usuModifica;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }




}


